apiVersion: v1
name: onecx-search-config-svc
version: 0.0.0
appVersion: 0.0.0
description: Onecx search config service
keywords:
  - search-config
sources:
  - https://github.com/onecx/onecx-search-config-svc
maintainers:
  - name: Tkit Developer
    email: tkit_dev@1000kit.org
dependencies:
  - name: helm-quarkus-app
    alias: app
    version: ^0
    repository: oci://ghcr.io/onecx/charts