openapi: "3.0.3"
info:
  title: onecx-search-config-svc
  version: "1.0"
servers:
  - url: https://onecx-search-config-svc/
tags:
  - name: SearchConfigInternal
    description: Execute Search Config CRUD operations
paths:
  /internal/searchConfig:
    post:
      security:
        - oauth2: [ ocx-sc:all, ocx-sc:write ]
      tags:
        - SearchConfigInternal
      summary: Creates the search config.
      description: Creates the search config.
      operationId: createConfig
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/CreateSearchConfigRequest'
      responses:
        "201":
          description: Created
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/SearchConfig'
        "400":
          description: Bad request
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ProblemDetailResponse'
  /internal/searchConfig/search:
    post:
      security:
        - oauth2: [ ocx-sc:all, ocx-sc:read ]
      tags:
        - SearchConfigInternal
      summary: Finds search configs by criteria.
      description: The search configs are found by search criteria.
      operationId: findBySearchCriteria
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/SearchConfigSearchRequest'
      responses:
        "200":
          description: OK
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/SearchConfigPageResult'
        "400":
          description: Bad request
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ProblemDetailResponse'
  /internal/searchConfig/load:
    post:
      security:
        - oauth2: [ ocx-sc:all, ocx-sc:read ]
      tags:
        - SearchConfigInternal
      summary: Finds search configs by product, app and page.
      description: The search configs are found by the criteria product, app and page.
      operationId: loadByProductAppAndPage
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/SearchConfigLoadRequest'
      responses:
        "200":
          description: OK
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/SearchConfigLoadResult'
        "400":
          description: Bad request
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ProblemDetailResponse'
  /internal/searchConfig/{id}:
    get:
      security:
        - oauth2: [ ocx-sc:all, ocx-sc:read ]
      tags:
        - SearchConfigInternal
      summary: Finds search configs by it's id.
      description: Gets the search config by it's id.
      operationId: getConfigById
      parameters:
        - name: id
          in: path
          required: true
          schema:
            type: string
      responses:
        "200":
          description: OK
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/SearchConfig'
        "404":
          description: Not found
    put:
      security:
        - oauth2: [ ocx-sc:all, ocx-sc:write ]
      tags:
        - SearchConfigInternal
      summary: Updates the search config.
      description: Updates the search config.
      operationId: updateConfig
      parameters:
        - name: id
          in: path
          required: true
          schema:
            type: string
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/UpdateSearchConfigRequest'
      responses:
        "200":
          description: OK
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/SearchConfig'
        "400":
          description: Bad request
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ProblemDetailResponse'
        "404":
          description: Search-config not found
    delete:
      security:
        - oauth2: [ ocx-sc:all, ocx-sc:delete ]
      tags:
        - SearchConfigInternal
      summary: Deletes the search config.
      description: Deletes the search config.
      operationId: deleteConfig
      parameters:
        - name: id
          in: path
          required: true
          schema:
            type: string
      responses:
        "204":
          description: Config deleted
        "400":
          description: Internal Server Error
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ProblemDetailResponse'
components:
  securitySchemes:
    oauth2:
      type: oauth2
      flows:
        clientCredentials:
          tokenUrl: https://oauth.simple.api/token
          scopes:
            ocx-sc:all: Grants access to all operations
            ocx-sc:read: Grants read access
            ocx-sc:write: Grants write access
            ocx-sc:delete: Grants access to delete operations
  schemas:
    OffsetDateTime:
      format: date-time
      type: string
      example: 2022-03-10T12:15:50-04:00
    SearchConfig:
      type: object
      properties:
        creationDate:
          $ref: '#/components/schemas/OffsetDateTime'
        creationUser:
          type: string
        modificationDate:
          $ref: '#/components/schemas/OffsetDateTime'
        modificationUser:
          type: string
        id:
          type: string
        appId:
          type: string
        page:
          type: string
        name:
          type: string
        productName:
          type: string
        columns:
          type: array
          items:
            type: string
        values:
          type: object
          additionalProperties:
            type: string
        modificationCount:
          format: int32
          type: integer
        fieldListVersion:
          type: integer
          description: Version increment of the fields in the UI which you should use when you are making incompatible changes to those fields.
        readOnly:
          type: boolean
          description: Defines whether this config can be changed in the UI
        advanced:
          type: boolean
          description: Indicates whether the advanced mode should be displayed
    SearchConfigResult:
      type: object
      properties:
        creationDate:
          $ref: '#/components/schemas/OffsetDateTime'
        creationUser:
          type: string
        modificationDate:
          $ref: '#/components/schemas/OffsetDateTime'
        modificationUser:
          type: string
        id:
          type: string
        appId:
          type: string
        page:
          type: string
        name:
          type: string
        productName:
          type: string
        modificationCount:
          format: int32
          type: integer
        fieldListVersion:
          type: integer
          description: Version increment of the fields in the UI which you should use when you are making incompatible changes to those fields.
        readOnly:
          type: boolean
          description: Defines whether this config can be changed in the UI
        advanced:
          type: boolean
          description: Indicates whether the advanced mode should be displayed
    CreateSearchConfigRequest:
      type: object
      required:
        - productName
        - page
        - name
        - appId
        - columns
        - values
      properties:
        productName:
          type: string
        page:
          type: string
        name:
          type: string
        appId:
          type: string
        fieldListVersion:
          type: integer
          description: Version increment of the fields in the UI which you should use when you are making incompatible changes to those fields.
        readOnly:
          type: boolean
          description: Defines whether this config can be changed in the UI
        advanced:
          type: boolean
          description: Indicates whether the advanced mode should be displayed
        columns:
          type: array
          items:
            type: string
        values:
          type: object
          additionalProperties:
            type: string
    SearchConfigSearchRequest:
      type: object
      properties:
        productName:
          type: string
        name:
          type: string
        appId:
          type: string
        page:
          type: string
        pageNumber:
          format: int32
          description: The number of page.
          default: 0
          type: integer
        pageSize:
          format: int32
          description: The size of page
          default: 100
          type: integer
    SearchConfigLoadRequest:
      type: object
      required:
        - productName
        - appId
        - page
      properties:
        productName:
          type: string
        appId:
          type: string
        page:
          type: string
    UpdateSearchConfigRequest:
      type: object
      required:
        - modificationCount
      properties:
        page:
          type: string
        name:
          type: string
        appId:
          type: string
        productName:
          type: string
        modificationCount:
          type: integer
        fieldListVersion:
          type: integer
          description: Version increment of the fields in the UI which you should use when you are making incompatible changes to those fields.
        readOnly:
          type: boolean
          description: Defines whether this config can be changed in the UI
        advanced:
          type: boolean
          description: Indicates whether the advanced mode should be displayed
        columns:
          type: array
          items:
            type: string
        values:
          type: object
          additionalProperties:
            type: string
    SearchConfigPageResult:
      type: object
      properties:
        totalElements:
          format: int64
          description: The total elements in the resource.
          type: integer
        number:
          format: int32
          type: integer
        size:
          format: int32
          type: integer
        totalPages:
          format: int64
          type: integer
        stream:
          type: array
          items:
            $ref: '#/components/schemas/SearchConfigResult'
    SearchConfigLoadResult:
      type: object
      properties:
        id:
          type: string
        name:
          type: string
        columns:
          type: array
          items:
            type: string
        values:
          type: object
          additionalProperties:
            type: string
        readOnly:
          type: boolean
          description: Defines whether this config can be changed in the UI
        advanced:
          type: boolean
          description: Indicates whether the advanced mode should be displayed
    ProblemDetailResponse:
      type: object
      properties:
        errorCode:
          type: string
        detail:
          type: string
        params:
          type: array
          items:
            $ref: '#/components/schemas/ProblemDetailParam'
        invalidParams:
          type: array
          items:
            $ref: '#/components/schemas/ProblemDetailInvalidParam'
    ProblemDetailParam:
      type: object
      properties:
        key:
          type: string
        value:
          type: string
    ProblemDetailInvalidParam:
      type: object
      properties:
        name:
          type: string
        message:
          type: string